# This file was generated by GoReleaser. DO NOT EDIT.
cask "ryvn" do
  name "ryvn"
  desc "Deploy to any customer cloud via a single control plane"
  homepage "https://ryvn.ai/"
  version "0.140.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ryvn"

  on_macos do
    on_intel do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v#{version}/ryvn-cli-release_Darwin_x86_64.tar.gz"
      sha256 "e6ce74e0b444c35fffad86695dc4ca3f1b0142a2fea3cc13a37ea21ddc0d6923"
    end
    on_arm do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v#{version}/ryvn-cli-release_Darwin_arm64.tar.gz"
      sha256 "d118beff397abea679a9ae002eb1619d1cfe3b290173a485413395fa3a90a011"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v#{version}/ryvn-cli-release_Linux_x86_64.tar.gz"
      sha256 "4b3683ffd12970212e752bb83b1c80971bf5e230b165b18238d5fe6007c284b1"
    end
    on_arm do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v#{version}/ryvn-cli-release_Linux_arm64.tar.gz"
      sha256 "60fe98e73e0fa2d9dfd3f915a537f9f53254fdd4700058fd125d6ef37971f5a8"
    end
  end

  # No zap stanza required
end
