# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ryvn < Formula
  desc "Deploy to any customer cloud via a single control plane"
  homepage "https://ryvn.ai/"
  version "0.38.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v0.38.0/ryvn-cli-release_Darwin_x86_64.tar.gz"
      sha256 "545d0934a5c0bd004f090d523edd3eb6658ff96ce8268c42420aa169f39f7386"

      def install
        bin.install "ryvn"
      end
    end
    on_arm do
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v0.38.0/ryvn-cli-release_Darwin_arm64.tar.gz"
      sha256 "1a13c3067476ebedea648678147b4266ebb5187cfbcdda40eb3a1b19cd82f8b7"

      def install
        bin.install "ryvn"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v0.38.0/ryvn-cli-release_Linux_x86_64.tar.gz"
        sha256 "b76188705c4eaa2f761e49e80bc3ba16683f7377aea950a261e799ed215ca58f"

        def install
          bin.install "ryvn"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v0.38.0/ryvn-cli-release_Linux_arm64.tar.gz"
        sha256 "31ef796ef6165cb92cd7544320a03b879d4d608b3c3aa4c5d274f1260462e1bb"

        def install
          bin.install "ryvn"
        end
      end
    end
  end
end
