# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ryvn < Formula
  desc "Deploy to any customer cloud via a single control plane"
  homepage "https://ryvn.ai/"
  version "1.272.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v1.272.0/ryvn-cli-release_Darwin_x86_64.tar.gz"
      sha256 "360fa51ee47f30eb352efe0a8f48f21cae9543fddf731e49325c992a2c5926fb"

      define_method(:install) do
        bin.install "ryvn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v1.272.0/ryvn-cli-release_Darwin_arm64.tar.gz"
      sha256 "24f9514ff9ec4aeb11e0dd516a2f0a6701085ad55f0baa4c75a7810706434368"

      define_method(:install) do
        bin.install "ryvn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v1.272.0/ryvn-cli-release_Linux_x86_64.tar.gz"
      sha256 "fd2b473cfb598223f1dfde6055b6cf4954396592e874b3b3fa97d3c91fcb3868"
      define_method(:install) do
        bin.install "ryvn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryvn-technologies/ryvn-cli-release/releases/download/v1.272.0/ryvn-cli-release_Linux_arm64.tar.gz"
      sha256 "89fe30115a24488cc10a591a8d09149d56499f43981193c7ef23fc6080b9ccde"
      define_method(:install) do
        bin.install "ryvn"
      end
    end
  end
end
